@startuml "gantt"
language fr
printscale weekly
sunday are closed
2021-10-23 to 2021-11-01 is closed
2021-11-11 is closed
2021-11-02 to 2021-11-04 are named [Crunch]

Project starts 2021-09-10
-- Analyse --
[Analyse générale du sujet] starts 2021-09-10 and ends 2021-09-15
[Réalisation du diagramme de cas d’utilisation] starts 2021-09-16 and ends 2021-09-16
[Analyse générale du sujet] -> [Réalisation du diagramme de cas d’utilisation]
[Répartition des rôles] happens 2021-09-17
[Exploration de l’API Base Adresse Nationale] starts 2021-09-17 and ends 2021-09-17
[Rédaction individuelle de squelettes de rapport intermédiaire] starts 2021-09-20 and ends 2021-09-30
[Mise en commun des squelettes de rapport] happens 2021-10-01
[Rédaction individuelle de squelettes de rapport intermédiaire] -> [Mise en commun des squelettes de rapport]
[Finalisation du plan définitif du rapport intermédiaire] starts 2021-10-01 and ends 2021-10-01
[Mise en commun des squelettes de rapport] -> [Finalisation du plan définitif du rapport intermédiaire]
[Conception générale des différents diagrammes du rapport intermédiaire] starts 2021-10-01 and ends 2021-10-04
[Diagramme d’état des fiches adresse] starts 2021-10-05 and ends 2021-10-11
[Conception générale des différents diagrammes du rapport intermédiaire] -> [Diagramme d’état des fiches adresse]
[Diagramme d’activité portant sur la reprise des fiches adresse] starts 2021-10-08 and ends 2021-10-08
[Conception générale des différents diagrammes du rapport intermédiaire] -> [Diagramme d’activité portant sur la reprise des fiches adresse]
[Diagramme d’activité portant sur l’attribution des lots de fiches aux agents] starts 2021-10-08 and ends 2021-10-11
[Conception générale des différents diagrammes du rapport intermédiaire] -> [Diagramme d’activité portant sur l’attribution des lots de fiches aux agents]
[Diagramme de séquence portant sur l'API BAN] starts 2021-10-08 and ends 2021-10-13
[Conception générale des différents diagrammes du rapport intermédiaire] -> [Diagramme de séquence portant sur l'API BAN]
[Réunion de finalisation des diagrammes du rapport intermédiaire] happens 2021-10-11
[Mise en place d’un planning prévisionnel pour la phase de développement] happens 2021-10-11
[Rédaction du rapport intermédiaire] starts 2021-10-01 and ends 2021-10-15
[Rendu du rapport intermédiaire] happens 2021-10-16
[Rédaction du rapport intermédiaire] -> [Rendu du rapport intermédiaire]
-- Développement --
[Sprint 1 : Fonctions Mono-Utilisateur] starts 2021-10-18 and ends 2021-10-22
[Sprint 2 : Fonctions Multi-Utilisateur] starts 2021-11-02 and ends 2021-11-10
[Sprint 3 : Fonctions Avancées] starts 2021-11-11 and ends 2021-11-26
[Rédaction du rapport final] starts 2021-11-15 and ends 2021-11-26
[Rendu du rapport final] happens 2021-11-26
-- Soutenance --
[Préparation de la soutenance] starts 2021-11-29 and ends 2021-12-07
[Soutenance] happens 2021-12-07
@enduml