@startuml "uml_activite_repartition"
skinparam ConditionEndStyle hline
start
group Sélection des agents
fork
:Chargement de la liste des agents;
:Sélection du premier agent de la liste;
repeat :Lecture du pot de l'agent;
    :Récupération du nombre de 
    fiches dans le pot de l'agent;
    :Calcul de la capacité de travail de l'agent;
backward:Sélection de l'agent suivant;
repeat while (Dernier agent atteint ?) is (non) not (oui)
:Affichage de la liste des agents
et de leur capacité de travail;
fork again
:Récupération du nombre de
fiches à reprendre;
:Affichage du travail total
de reprise à affecter;
end merge
:Sélection des agents par le superviseur;
:Calcul de la capacité de travail totale
des agents sélectionnés;
end group
group Répartition des fiches
:Initialisation d'une
proposition de répartition;
if (Capacité inférieure au nombre de fiches à reprendre ?) then (oui)
    :Saturation de la capacité de
    travail de chaque agent;
    :Répartition des fiches supplémentaires
    au prorata de la quotité;
else (non)
    :Calcul du nombre de fiches
    pouvant être contrôlées;
    :Saturation de la capacité de
    travail de chaque agent;
endif
:Affichage de la proposition de répartition;
if (Proposition validée par le superviseur ?) then (oui)
else (non)
    :Modification manuelle de la répartition;
endif
if (Nombre de fiches à contrôler > 0 ?) then (oui)
    :Echantillonnage de la liste des
    fiches traitées par l'API;
    :Fusion des listes de contrôle
    et de reprise;
else (non)
endif
end group
:Application de la répartition
dans le pot des agents;
stop
@enduml