@startuml "uml_activite_repartition"
skinparam ConditionEndStyle hline
start
group Affectation
fork
:Chargement de la liste des agents;
:Sélection du premier agent de la liste;
repeat :Lecture du pot de l'agent;
    :Récupération du nombre de 
    fiches dans le pot de l'agent;
    :Calcul de la capacité de travail de l'agent;
backward:Sélection de l'agent suivant;
repeat while (Dernier agent atteint ?) is ([non]) not ([oui])
:Affichage de la liste des agents
et de leur capacité de travail;
fork again
:Récupération du nombre de
fiches à reprendre;
:Affichage du travail total
de reprise à affecter;
end fork
:Sélection des agents par le superviseur;
:Affectation d'une quantité de travail à
chaque agent sélectionné par le superviseur;
:Calcul du nombre total
de fiches affectées;
end group
group Répartiton
if (Nombre de fiches affectées > Nombre de fiches à reprendre ?) then ([oui])
    :Calcul du nombre de fiches à contrôler;
    :Echantillonnage de la liste des
    fiches traitées par l'API;
    :Fusion des listes de contrôle
    et de reprise;
else ([non])
endif
end group
:Application de la répartition
dans le pot des agents;
stop
@enduml